sudo: required
dist: trusty
language: cpp
cache: apt

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
  - BUILD_TYPE=RelWithDebInfo

addons:
  apt:
    packages:
      - valgrind

script:
  - scons CXX=`which $CXX` BUILD_TYPE=$BUILD_TYPE test
  - if [[ "$BUILD_TYPE" == "Debug" ]]; then valgrind --suppressions=etc/valgrind.suppressions --tool=helgrind --gen-suppressions=all --error-exitcode=1 --read-var-info=yes ./build/test_runner; fi
  - valgrind --suppressions=etc/valgrind.suppressions --tool=memcheck --leak-check=full --gen-suppressions=all --error-exitcode=1 --read-var-info=yes ./build/test_runner

  - if [[ "$CC" == "clang" ]]; then scons CXX=`which $CXX` CLANG_SANITIZE=thread test; fi
  - if [[ "$CC" == "clang" ]]; then scons CXX=`which $CXX` CLANG_SANITIZE=address test; fi
  - if [[ "$CC" == "clang" ]]; then scons CXX=`which $CXX` CLANG_SANITIZE=undefined test; fi

  - if [[ "$BUILD_TYPE" == "Release" ]]; then scons CXX=`which $CXX` BUILD_TYPE=$BUILD_TYPE benchmark; fi
