version: "1.0.{build}"
os: Visual Studio 2015
platform:
  - Win32

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    PYTHON: "C:\\Python27"
  matrix:
    - BUILD_TYPE: "Debug"
      MSVS_VERSION: "14.0"
    - BUILD_TYPE: "Release"
      MSVS_VERSION: "14.0"
    - BUILD_TYPE: "RelWithDebInfo"
      MSVS_VERSION: "14.0"
    - BUILD_TYPE: "Debug"
      MSVS_VERSION: "12.0"
    - BUILD_TYPE: "Release"
      MSVS_VERSION: "12.0"
    - BUILD_TYPE: "RelWithDebInfo"
      MSVS_VERSION: "12.0"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  - git submodule update --init --recursive

build_script:
  - scons.py BUILD_TYPE=%BUILD_TYPE% MSVS_VERSION=%MSVS_VERSION% test
  - if "%BUILD_TYPE%"=="Release" scons BUILD_TYPE=%BUILD_TYPE% MSVS_VERSION=%MSVS_VERSION% benchmark
