version: "1.0.{build}"
os: Visual Studio 2015
platform:
  - Win32

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    PYTHON: "C:\\Python27"
  matrix:
    - BUILD_TYPE: "Debug"
    - BUILD_TYPE: "Release"
    - BUILD_TYPE: "RelWithDebInfo"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  - git submodule update --init --recursive

build_script:
  - scons.py BUILD_TYPE=%BUILD_TYPE% test
  - if "%BUILD_TYPE%"=="Release" scons BUILD_TYPE=$BUILD_TYPE benchmark
