version: "1.0.{build}"
os: Visual Studio 2015
platform:
  - Win32

environment:
  global:
    MSVC_DEFAULT_OPTIONS: ON
    PYTHON: "C:\\Python27"

install:
  - SET "PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - easy_install scons
  - git submodule update --init --recursive

build_script:
  - scons.py

test_script:
  - scons.py test
